### PR TITLE
Update images for 8.7 what's new

### PR DESCRIPTION
**Pull request by borja-munoz**
- Update image for MaskExtension
- Add image for fetchMap

### CODE REVIEW

**Review by ibgreen — COMMENTED** [review]
I don't feel that it is appropriate to have screenshot of CARTO products in deck.gl's what's new.

**Comment by Pessimistress** [comment]
Agreed. Also the new mask-extension.gif resolution is too low.

**Review by alasarr — APPROVED** [review]

**Comment by alasarr** [comment]
Sorry, I didn't see your comments and I merged...rolling back

**Comment by alasarr** [comment]
Main restored

**Comment by alasarr** [comment]
>I don't feel that it is appropriate to have screenshot of CARTO products in deck.gl's what's new.

We didn't try to make a commercial push around CARTO here. It's just because the fetchMap procedure is a very important feature for CARTO module now and it's used together with CARTO UI, it will let the users understand better the feature.

@borja-munoz let's move this image to CARTO's internal doc, and link from whats-new there. 

Can you improve the resolution?

**Pull request merged**
