### PR TITLE
feat: more geoparquet datasets

### PR DESCRIPTION
**Pull request by belom88**

### CODE REVIEW

**Review by ibgreen — COMMENTED** [review]
What is the license of these datasets? If they are OSM licensed, we may need to be a bit careful and maybe create a deck.gl-data-osm repo. There has been flags raised about some provision in the OSM license in the past.

**Review by ibgreen — COMMENTED** [review]
Please update https://github.com/visgl/deck.gl-data/tree/master/formats

**Comment by belom88** [comment]
I've found Fort Collins data on https://www.fcgov.com/gis/downloadable-data. It seems datasets are open

**Comment by ibgreen** [comment]
> I've found Fort Collins data on https://www.fcgov.com/gis/downloadable-data. It seems datasets are open

That is fine, if you can add links to the sources that should be enough.

**Review by ibgreen — APPROVED** [review]

**Pull request merged**
